### ISSUE TITLE
No user dictionary in 2.99.6 (beta)

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-android#20]

**Comment by Rawa** [comment]
Could you please provide a more accurate error/issue description. Long press on comma ( , ) to see the settings menu and then you can enter the personal dictionaries to see what words has been added or add more manually.

**Comment by snomos** [comment]
I had expected access to the user dictionary in the keyboard app, similar to what is done in the iOS w.

**Comment by Rawa** [comment]
I've added it to the settings fragment. The personalized dictionaries are now reachable from the settings as well.
