### ISSUE TITLE
Letters with combining diacritics smaller than precomposed letters

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-android#28]
![sjd-4row-android](https://user-images.githubusercontent.com/1255285/133123588-48f793c1-2825-4db2-ab09-223d2d2a39b0.png)

Hypothesis: Android counts number of codepoints, not character class, and concludes there are "two" letters, thus they must be smaller to fit. The proper solution would be to ignore codepoints that belong to the Nonspacing_Mark (`Mn`) unicode class, or to any Combining class.

But the cause can of course be something completely different.

**Comment by Trondtr** [comment]
The theory fits the data, so I think you are right. This seems to be a bug for Android.

**Comment by snomos** [comment]
As shown in the screenshot in https://github.com/divvun/giellakbd-android/issues/35, this is already fixed. Closing.
