### ISSUE TITLE
Keyboard crashes on startup, makes it unusable

### ISSUE THREAD

**Issue by albbas** [divvun/giellakbd-android#33]
On startup, either using the North Sami or Inari Sami keyboard, the app crashes.

This happens on a Samsung A52s, the model number is SM-A528B/DS.
![samsungA52](https://user-images.githubusercontent.com/75695/212858299-18b1a8b1-2736-4b4a-b6e8-d4b63eeaba7a.jpg)

**Comment by zoomix** [comment]
This should be fixed with 0.2.4 of divvun-dev-keyboard. LMK if it works =)

**Comment by snomos** [comment]
@albbas is it fixed on your phone?

**Comment by albbas** [comment]
Version 1.1.0 works fine for me, spelling and everything. I have a Motorola Edge 30 Pro.

**Comment by snomos** [comment]
Good, then we can close this issue.
