### ISSUE TITLE
Keys skewed to left in recent versions

### ISSUE THREAD

**Issue by snomos** [divvun/giellakbd-android#35]
![Screenshot_20230828_143554_com whatsapp](https://github.com/divvun/giellakbd-android/assets/1255285/a5467a6b-ed10-4cca-a683-c332315bec05)

This is true for the SJD, SME and SMJ keyboards, probably other keyboards. This started with an Android update this summer using automatic updates. Possibly after system upgrades to Android 13. Nothing has changed with the actual keyboards during this period.

**Comment by snomos** [comment]
@albbas can you reproduce, and maybe give some more details about system, device etc?

**Comment by albbas** [comment]
Still skewed on my phone.

Divvun keyboard version 3.2.1
Phone: Motorola Edge 30 pro (XT2201-1)
Android version: 13

Is anymore info needed?

**Comment by albbas** [comment]
The keyboard is skewed in the Divvun Dev keyboard, as well

**Comment by zoomix** [comment]
=(

Tried this on a Samsung z flip 3&4, LG G7, Google Pixel 5, a Samsung table and a Lenovo tablet. None of them exhibit the same behavior. On the other hand, none of them have the exact same screen.. Hmm.. Grr. 

I tried running the emulator with the exact specification of the Motorola 30 Edge Pro too - no dice =/

Do you know if you've changed anything peculiar about the phone? No font-sizes, zoom levels, accessories or anything like that I'd need to know of?

Also - would you mind downloading "CPU Z" and posting some screenshots of the "Device" and "System" tabs? Should look something like this.

![image](https://github.com/divvun/giellakbd-android/assets/813082/12048150-fc87-4407-8a36-5d2bf2b021c8)

**Comment by albbas** [comment]
![Screenshot_20231026-095202](https://github.com/divvun/giellakbd-android/assets/75695/975f3afc-bb45-4af5-a9db-63f40e8ac24e)
![Screenshot_20231026-095152](https://github.com/divvun/giellakbd-android/assets/75695/38dd6bae-5ab4-44a2-bf6d-5b01cddc29ea)

**Comment by zoomix** [comment]
@albbas - shucks =/.  I noticed you had a different phone earlier. Could you maybe see if you see the same problem on that device too?

This is the reference. 
https://github.com/divvun/giellakbd-android/issues/33

@snomos did we hear this problem from anyone else on any other device?

**Comment by snomos** [comment]
> @snomos did we hear this problem from anyone else on any other device?

Yes, the screen shot in the first message is from another user.

**Comment by albbas** [comment]
I sent a Nokia to TTC a few years ago, it was a problematic phone, as well. If that's still around, that may be a candidate. 

By the way, tried installing Divvun Dev on a Nothing Phone, by the way. No problems there. I'll look for more devices.

**Comment by zoomix** [comment]
Now tried on an CAT s62, Alcatel, an older Motorla and a cheapo samsung A105fn.. No problems with any of them. 

Would you be willing to hack a little bit If you take this barebones unprocessed keyboard APK and load it on your Motorola Edge 30 Pro - does it exhibit the same behavior?

https://drive.google.com/file/d/1CZaalmOkv7rx2ENoKt94TXoq0GR47VNY/view?usp=sharing

**Comment by albbas** [comment]
Tried it, it looks good :)

**Comment by albbas** [comment]
But the test app crashes often, I get a message once in a while about that.

**Comment by albbas** [comment]
Tried removing and reinstalling both the regular Divvun and Divvun-dev keyboards. The keys are still skewed …

**Comment by albbas** [comment]
Could there be some empty keys to the right of the visible keys in the Divvun-keyboards?

**Comment by ena-fly** [comment]
Hi @albbas can you please try [this version](https://github.com/divvun/giellakbd-android/files/13416369/keyboard.zip) and see if the keys are still skewed?

**Comment by ena-fly** [comment]
Also Now I noticed the difference in number of letters in @zoomix [video](https://github.com/divvun/giellakbd-android/issues/35#issuecomment-1779185986) and [this image](https://github.com/divvun/giellakbd-android/issues/35#issue-1871743221). 

So we should explore what is the reason behind not seeing all the letters.

**Comment by albbas** [comment]
> Hi @albbas can you please try [this version](https://github.com/divvun/giellakbd-android/files/13416369/keyboard.zip) and see if the keys are still skewed?

I unzipped it and downloaded it to Google Disk. When I tried to open it on the phone it says it is an invalid package. Am I doing something wrong?

**Comment by albbas** [comment]
Ok, fixed settings to be able to install it, but then it says I can't install this app on my device.

**Comment by ena-fly** [comment]
@albbas Do you have time to have a video chat with @zoomix  and me so we can get to the bottom of this?

**Comment by ena-fly** [comment]
Thank you, and in the meantime can you try to install and download [this version](https://drive.google.com/file/d/1-xVHcblvO-TNZSfmxIqFdRQnVnurveRN/view?usp=sharing)?

**Comment by ena-fly** [comment]
Hmm okay, that is good. So this problem with skewed layout occurs in version 3.2.0?

**Comment by albbas** [comment]
I have Divvun keyboards 3.2.1 on my phone, and that's affected. Divvun dev (0.2.3) found on Google Play is affected, as well (threw out the version above, and installed the Google Play version)

**Comment by zoomix** [comment]
This is now deployed as version 0.2.4 of divvun-dev-keyboard in android store. LMK if it works. It's looking good over here

**Comment by dylanhand** [comment]
@snomos is this fix working for you? Let me know if you're ready for me to push a release.

**Comment by dylanhand** [comment]
I think it's best we wait until after the holidays :)

**Comment by snomos** [comment]
Agreed, we wait.

**Comment by snomos** [comment]
Divvun Dev keyboards released, and this issue is fixed. We still need to release the regular Divvun keyboard, but this issue can be closed as fixed.
