### ISSUE TITLE
Update app to work on latest Android devices/SDK

### ISSUE THREAD

**Issue by dylanhand** [divvun/giellakbd-android#41]
User was unable to install keyboard app on Android 14 but says the app isn't supported on newer versions of Android.

**Comment by snomos** [comment]
I have asked the OP for more information.

**Comment by snomos** [comment]
This is the information received:

> Har Samsung Galaxy S23 Ultra
Modellnavn: SM-S918B/DS
Android versjon: 14
One UI-Versjon: 6.1
Kjerneversjon: 5.15-123-Android13-8-28577312-abS91BXXS3CXD2
RAM 8GB

**Comment by dylanhand** [comment]
Reproduced.

Managed to find someone with a Samsung Galaxy S23 (not Ultra), and the Play Store also alerted that the app wasn't supported on newer versions of Android.

**Samsung Galaxy S23** Screenshots of Play Store listing of Divvun Keyboards and OS version:
<img src="https://github.com/divvun/giellakbd-android/assets/431529/1989e008-d314-4f9b-b907-2384d791ce28" width="300" />
<img src="https://github.com/divvun/giellakbd-android/assets/431529/c73d5c78-c7a0-4476-add2-bb104d611ce7" width="300" />


This appears to only affect some devices, or perhaps only Samsung. This same issue does **not** occur on a **Google Pixel 6 Pro** which is also running Android 14:

<img src="https://github.com/divvun/giellakbd-android/assets/431529/d67308b4-7e16-4886-b816-6fb15ece4f4d" width="300" />
<img src="https://github.com/divvun/giellakbd-android/assets/431529/d8198b39-2b7a-425b-9306-0fd988d9fe12" width="300" />
<img src="https://github.com/divvun/giellakbd-android/assets/431529/e5f3946b-92d8-4fea-a130-09fdff7582b3" width="300" />

**Comment by dylanhand** [comment]
I think the solution will be to update the Android SDK when we release the next build.

Once I have sign off on the bugs listed in https://github.com/divvun/maintenance2023/issues/1, I can update the SDK and release a new version that will hopefully fix this issue.

**Comment by zoomix** [comment]
Updated divvun-dev-keyboards to SDK 34 and tested on android 13 & 14, tablet and phone. 

Looks ok, but I'm not sure what the state of each individual keyboard is supposed to be so I can't be certain. 
If this is ok, next android build will be using sdk 34.

@snomos , can you verify or direct it to someone who can? divvun-dev keyboard is on open testing and is updated 22 Aug 2024

**Comment by snomos** [comment]
@albbas @kathiasi & @flammie can you try to get the new open beta version, and see if it works as it should? Please report here 🙂

**Comment by flammie** [comment]
the crash of #39 is still there in the settings, however long holding the globe button of gboard now shows Apurinã Livonian Keyboard(!) instead of Erzya in the listing of available keyboards somehow.

**Comment by zoomix** [comment]
That's.. actually an endorsement. That sounds like SDK 34 update (Android 14 update) didn't break anything other than what was already broken. Good. 👍

**Comment by snomos** [comment]
This seems to be working as expected (ie no new bugs introduced). Assume fixed.
